phases:
- phase: Windows
  queue:
    name: Perf Pool - Windows
    timeoutInMinutes: 90
    parallel: 1
    matrix:
      ci_part2:
        _command: build.cmd
        _args: release ci_part2
  steps:
    - script: $(_command) $(_args)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\tests\TestResults'
        ArtifactName: 'Windows $(_command) $(_args)'
        publishLocation: Container
      continueOnError: true
      condition: failed()
